# data
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_XSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 72
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: False

# model
model: model_hacm.transformer.Transformer
model_args:
  dim_in: 3
  dim_feat: 256
  decoder_dim_feat: 256
  depth: 8
  decoder_depth: 3
  num_heads: 8
  mlp_ratio: 4
  num_frames: 72
  num_joints: 18
  patch_size: 1
  t_patch_size: 3
  qkv_bias: True
  qk_scale: None
  drop_rate: 0.
  attn_drop_rate: 0.
  drop_path_rate: 0.
  norm_skes_loss: True

# training
epochs: 400
warmup_epochs: 20
batch_size: 64
lr: 1e-3
min_lr: 5e-4
weight_decay: 0.05
mask_ratio: 0.9
motion_aware_tau: 0.75
